In [15]:
import numpy as np
import pandas as pd

In [16]:


xls = pd.ExcelFile('Uncertainity_Data\Global_Policy_Uncertainty_Data.xlsx')
EPU = xls.parse('Sheet1', header=0,index_col=None, na_values=['NA'])
#EPU Economic Politic Uncertainity

In [17]:
EPU

     Year  Month  GEPU_current    GEPU_ppp
0    1997      1     79.887326   84.434112
1    1997      2     83.145863   87.400304
2    1997      3     71.464942   71.169520
3    1997      4     77.521001   81.232802
4    1997      5     73.366201   75.143463
5    1997      6     81.379689   84.089595
6    1997      7     65.854587   63.687001
7    1997      8     64.929356   60.654351
8    1997      9     68.045255   64.332455
9    1997     10     82.110431   78.508219
10   1997     11     93.205424   85.053490
11   1997     12    104.295953   92.002334
12   1998      1     96.828275   89.943329
13   1998      2     86.752832   82.417343
14   1998      3     89.827865   84.357993
15   1998      4     79.984998   71.842271
16   1998      5     86.817065   79.081366
17   1998      6     85.903175   80.389176
18   1998      7    103.423216   97.514967
19   1998      8    117.423873  109.187774
20   1998      9    151.405519  152.742571
21   1998     10    120.175145  114.670833
22   1998     11    100.382400   94.639219
23   1998     12     95.699437   94.640759
24   1999      1    101.756229  103.076170
25   1999      2     82.085271   80.490188
26   1999      3     66.560508   64.296328
27   1999      4     65.799329   61.070079
28   1999      5     71.468466   71.942923
29   1999      6     74.525600   75.049923
..    ...    ...           ...         ...
229  2016      2    163.508727  166.587906
230  2016      3    171.201672  178.822162
231  2016      4    146.201912  152.387125
232  2016      5    137.765889  138.932755
233  2016      6    254.508211  250.371104
234  2016      7    264.740864  267.799482
235  2016      8    150.526471  157.210418
236  2016      9    161.389229  173.330688
237  2016     10    140.759020  140.959417
238  2016     11    271.403445  269.712575
239  2016     12    257.913450  283.864211
240  2017      1    283.258467  307.697770
241  2017      2    215.893940  232.142136
242  2017      3    232.832843  250.074790
243  2017      4    183.892476  187.731566
244  2017      5    183.555789  195.548792
245  2017      6    164.909385  169.173015
246  2017      7    129.750907  126.186281
247  2017      8    140.371505  142.402238
248  2017      9    154.299458  160.980000
249  2017     10    155.587546  164.247691
250  2017     11    150.122991  156.094925
251  2017     12    148.339606  156.272337
252  2018      1    124.195251  113.285072
253  2018      2    120.639207  125.439096
254  2018      3    152.949261  146.642449
255  2018      4    146.428229  152.493728
256  2018      5    178.425456  184.283251
257  2018      6    189.152015  199.374624
258  2018      7    210.708161  226.676860

[259 rows x 4 columns]

In [18]:
EPU=EPU.reset_index()
EPU=EPU.dropna()

In [19]:
EPU

     index  Year  Month  GEPU_current    GEPU_ppp
0        0  1997      1     79.887326   84.434112
1        1  1997      2     83.145863   87.400304
2        2  1997      3     71.464942   71.169520
3        3  1997      4     77.521001   81.232802
4        4  1997      5     73.366201   75.143463
5        5  1997      6     81.379689   84.089595
6        6  1997      7     65.854587   63.687001
7        7  1997      8     64.929356   60.654351
8        8  1997      9     68.045255   64.332455
9        9  1997     10     82.110431   78.508219
10      10  1997     11     93.205424   85.053490
11      11  1997     12    104.295953   92.002334
12      12  1998      1     96.828275   89.943329
13      13  1998      2     86.752832   82.417343
14      14  1998      3     89.827865   84.357993
15      15  1998      4     79.984998   71.842271
16      16  1998      5     86.817065   79.081366
17      17  1998      6     85.903175   80.389176
18      18  1998      7    103.423216   97.514967
19      19  1998      8    117.423873  109.187774
20      20  1998      9    151.405519  152.742571
21      21  1998     10    120.175145  114.670833
22      22  1998     11    100.382400   94.639219
23      23  1998     12     95.699437   94.640759
24      24  1999      1    101.756229  103.076170
25      25  1999      2     82.085271   80.490188
26      26  1999      3     66.560508   64.296328
27      27  1999      4     65.799329   61.070079
28      28  1999      5     71.468466   71.942923
29      29  1999      6     74.525600   75.049923
..     ...   ...    ...           ...         ...
229    229  2016      2    163.508727  166.587906
230    230  2016      3    171.201672  178.822162
231    231  2016      4    146.201912  152.387125
232    232  2016      5    137.765889  138.932755
233    233  2016      6    254.508211  250.371104
234    234  2016      7    264.740864  267.799482
235    235  2016      8    150.526471  157.210418
236    236  2016      9    161.389229  173.330688
237    237  2016     10    140.759020  140.959417
238    238  2016     11    271.403445  269.712575
239    239  2016     12    257.913450  283.864211
240    240  2017      1    283.258467  307.697770
241    241  2017      2    215.893940  232.142136
242    242  2017      3    232.832843  250.074790
243    243  2017      4    183.892476  187.731566
244    244  2017      5    183.555789  195.548792
245    245  2017      6    164.909385  169.173015
246    246  2017      7    129.750907  126.186281
247    247  2017      8    140.371505  142.402238
248    248  2017      9    154.299458  160.980000
249    249  2017     10    155.587546  164.247691
250    250  2017     11    150.122991  156.094925
251    251  2017     12    148.339606  156.272337
252    252  2018      1    124.195251  113.285072
253    253  2018      2    120.639207  125.439096
254    254  2018      3    152.949261  146.642449
255    255  2018      4    146.428229  152.493728
256    256  2018      5    178.425456  184.283251
257    257  2018      6    189.152015  199.374624
258    258  2018      7    210.708161  226.676860

[259 rows x 5 columns]

In [20]:
EPU['Date']= (EPU['Year'].astype(int))*100+EPU['Month'].astype(int)
#EPU['level_0']*2
#EPU['level_1']
EPU

     index  Year  Month  GEPU_current    GEPU_ppp    Date
0        0  1997      1     79.887326   84.434112  199701
1        1  1997      2     83.145863   87.400304  199702
2        2  1997      3     71.464942   71.169520  199703
3        3  1997      4     77.521001   81.232802  199704
4        4  1997      5     73.366201   75.143463  199705
5        5  1997      6     81.379689   84.089595  199706
6        6  1997      7     65.854587   63.687001  199707
7        7  1997      8     64.929356   60.654351  199708
8        8  1997      9     68.045255   64.332455  199709
9        9  1997     10     82.110431   78.508219  199710
10      10  1997     11     93.205424   85.053490  199711
11      11  1997     12    104.295953   92.002334  199712
12      12  1998      1     96.828275   89.943329  199801
13      13  1998      2     86.752832   82.417343  199802
14      14  1998      3     89.827865   84.357993  199803
15      15  1998      4     79.984998   71.842271  199804
16      16  1998      5     86.817065   79.081366  199805
17      17  1998      6     85.903175   80.389176  199806
18      18  1998      7    103.423216   97.514967  199807
19      19  1998      8    117.423873  109.187774  199808
20      20  1998      9    151.405519  152.742571  199809
21      21  1998     10    120.175145  114.670833  199810
22      22  1998     11    100.382400   94.639219  199811
23      23  1998     12     95.699437   94.640759  199812
24      24  1999      1    101.756229  103.076170  199901
25      25  1999      2     82.085271   80.490188  199902
26      26  1999      3     66.560508   64.296328  199903
27      27  1999      4     65.799329   61.070079  199904
28      28  1999      5     71.468466   71.942923  199905
29      29  1999      6     74.525600   75.049923  199906
..     ...   ...    ...           ...         ...     ...
229    229  2016      2    163.508727  166.587906  201602
230    230  2016      3    171.201672  178.822162  201603
231    231  2016      4    146.201912  152.387125  201604
232    232  2016      5    137.765889  138.932755  201605
233    233  2016      6    254.508211  250.371104  201606
234    234  2016      7    264.740864  267.799482  201607
235    235  2016      8    150.526471  157.210418  201608
236    236  2016      9    161.389229  173.330688  201609
237    237  2016     10    140.759020  140.959417  201610
238    238  2016     11    271.403445  269.712575  201611
239    239  2016     12    257.913450  283.864211  201612
240    240  2017      1    283.258467  307.697770  201701
241    241  2017      2    215.893940  232.142136  201702
242    242  2017      3    232.832843  250.074790  201703
243    243  2017      4    183.892476  187.731566  201704
244    244  2017      5    183.555789  195.548792  201705
245    245  2017      6    164.909385  169.173015  201706
246    246  2017      7    129.750907  126.186281  201707
247    247  2017      8    140.371505  142.402238  201708
248    248  2017      9    154.299458  160.980000  201709
249    249  2017     10    155.587546  164.247691  201710
250    250  2017     11    150.122991  156.094925  201711
251    251  2017     12    148.339606  156.272337  201712
252    252  2018      1    124.195251  113.285072  201801
253    253  2018      2    120.639207  125.439096  201802
254    254  2018      3    152.949261  146.642449  201803
255    255  2018      4    146.428229  152.493728  201804
256    256  2018      5    178.425456  184.283251  201805
257    257  2018      6    189.152015  199.374624  201806
258    258  2018      7    210.708161  226.676860  201807

[259 rows x 6 columns]

In [21]:
EPU=EPU.rename(columns = {'GEPU_current':'EPU_World'})
#Zaman Kaydırması Yapmak için kullanıyor. 
#Butun veri zaman ekseni açısından tam ve sıralandıktan sonra yapılması gerekiyor
EPU['EPU_World-1'] = EPU['EPU_World'] .shift(1)
EPU['EPU_World-2'] = EPU['EPU_World'].shift(2)
EPU['EPU_World-3'] = EPU['EPU_World'].shift(3)
EPU['EPU_World-6'] = EPU['EPU_World'].shift(6)
EPU['EPU_World-12'] = EPU['EPU_World'].shift(12)

In [22]:
EPU

,index,Year,Month,EPU_World,GEPU_ppp,Date,EPU_World-1,EPU_World-2,EPU_World-3,EPU_World-6,EPU_World-12
0,0,1997,1,79.887326,84.434112,199701,NaN,NaN,NaN,NaN,NaN
1,1,1997,2,83.145863,87.400304,199702,79.887326,NaN,NaN,NaN,NaN
2,2,1997,3,71.464942,71.169520,199703,83.145863,79.887326,NaN,NaN,NaN
3,3,1997,4,77.521001,81.232802,199704,71.464942,83.145863,79.887326,NaN,NaN
4,4,1997,5,73.366201,75.143463,199705,77.521001,71.464942,83.145863,NaN,NaN
5,5,1997,6,81.379689,84.089595,199706,73.366201,77.521001,71.464942,NaN,NaN
6,6,1997,7,65.854587,63.687001,199707,81.379689,73.366201,77.521001,79.887326,NaN
7,7,1997,8,64.929356,60.654351,199708,65.854587,81.379689,73.366201,83.145863,NaN
8,8,1997,9,68.045255,64.332455,199709,64.929356,65.854587,81.379689,71.464942,NaN
9,9,1997,10,82.110431,78.508219,199710,68.045255,64.929356,65.854587,77.521001,NaN
10,10,1997,11,93.205424,85.053490,199711,82.110431,68.045255,64.929356,73.366201,NaN
11,11,1997,12,104.295953,92.002334,199712,93.205424,82.110431,68.045255,81.379689,NaN
12,12,1998,1,96.828275,89.943329,199801,104.295953,93.205424,82.110431,65.854587,79.887326
13,13,1998,2,86.752832,82.417343,199802,96.828275,104.295953,93.205424,64.929356,83.145863
14,14,1998,3,89.827865,84.357993,199803,86.752832,96.828275,104.295953,68.045255,71.464942
15,15,1998,4,79.984998,71.842271,199804,89.827865,86.752832,96.828275,82.110431,77.521001
16,16,1998,5,86.817065,79.081366,199805,79.984998,89.827865,86.752832,93.205424,73.366201
17,17,1998,6,85.903175,80.389176,199806,86.817065,79.984998,89.827865,104.295953,81.379689
18,18,1998,7,103.423216,97.514967,199807,85.903175,86.817065,79.984998,96.828275,65.854587
19,19,1998,8,117.423873,109.187774,199808,103.423216,85.903175,86.817065,86.752832,64.929356
20,20,1998,9,151.405519,152.742571,199809,117.423873,103.423216,85.903175,89.827865,68.045255
21,21,1998,10,120.175145,114.670833,199810,151.405519,117.423873,103.423216,79.984998,82.110431
22,22,1998,11,100.382400,94.639219,199811,120.175145,151.405519,117.423873,86.817065,93.205424
23,23,1998,12,95.699437,94.640759,199812,100.382400,120.175145,151.405519,85.903175,104.295953
24,24,1999,1,101.756229,103.076170,199901,95.699437,100.382400,120.175145,103.423216,96.828275
25,25,1999,2,82.085271,80.490188,199902,101.756229,95.699437,100.382400,117.423873,86.752832
26,26,1999,3,66.560508,64.296328,199903,82.085271,101.756229,95.699437,151.405519,89.827865
27,27,1999,4,65.799329,61.070079,199904,66.560508,82.085271,101.756229,120.175145,79.984998
28,28,1999,5,71.468466,71.942923,199905,65.799329,66.560508,82.085271,100.382400,86.817065
29,29,1999,6,74.525600,75.049923,199906,71.468466,65.799329,66.560508,95.699437,85.903175
...,...,...,...,...,...,...,...,...,...,...,...
229,229,2016,2,163.508727,166.587906,201602,156.064443,112.745006,95.912063,140.933731,108.206666
230,230,2016,3,171.201672,178.822162,201603,163.508727,156.064443,112.745006,192.516401,93.736800
231,231,2016,4,146.201912,152.387125,201604,171.201672,163.508727,156.064443,132.929122,101.033485
232,232,2016,5,137.765889,138.932755,201605,146.201912,171.201672,163.508727,95.912063,105.470778
233,233,2016,6,254.508211,250.371104,201606,137.765889,146.201912,171.201672,112.745006,114.230896
234,234,2016,7,264.740864,267.799482,201607,254.508211,137.765889,146.201912,156.064443,133.001067
235,235,2016,8,150.526471,157.210418,201608,264.740864,254.508211,137.765889,163.508727,140.933731
236,236,2016,9,161.389229,173.330688,201609,150.526471,264.740864,254.508211,171.201672,192.516401
237,237,2016,10,140.759020,140.959417,201610,161.389229,150.526471,264.740864,146.201912,132.929122
238,238,2016,11,271.403445,269.712575,201611,140.759020,161.389229,150.526471,137.765889,95.912063
239,239,2016,12,257.913450,283.864211,201612,271.403445,140.759020,161.389229,254.508211,112.745006
240,240,2017,1,283.258467,307.697770,201701,257.913450,271.403445,140.759020,264.740864,156.064443
241,241,2017,2,215.893940,232.142136,201702,283.258467,257.913450,271.403445,150.526471,163.508727
242,242,2017,3,232.832843,250.074790,201703,215.893940,283.258467,257.913450,161.389229,171.201672
243,243,2017,4,183.892476,187.731566,201704,232.832843,215.893940,283.258467,140.759020,146.201912
244,244,2017,5,183.555789,195.548792,201705,183.892476,232.832843,215.893940,271.403445,137.765889
245,245,2017,6,164.909385,169.173015,201706,183.555789,183.892476,232.832843,257.913450,254.508211
246,246,2017,7,129.750907,126.186281,201707,164.909385,183.555789,183.892476,283.258467,264.740864
247,247,2017,8,140.371505,142.402238,201708,129.750907,164.909385,183.555789,215.893940,150.526471
248,248,2017,9,154.299458,160.980000,201709,140.371505,129.750907,164.909385,232.832843,161.389229
249,249,2017,10,155.587546,164.247691,201710,154.299458,140.371505,129.750907,183.892476,140.759020
250,250,2017,11,150.122991,156.094925,201711,155.587546,154.299458,140.371505,183.555789,271.403445
251,251,2017,12,148.339606,156.272337,201712,150.122991,155.587546,154.299458,164.909385,257.913450
252,252,2018,1,124.195251,113.285072,201801,148.339606,150.122991,155.587546,129.750907,283.258467
253,253,2018,2,120.639207,125.439096,201802,124.195251,148.339606,150.122991,140.371505,215.893940
254,254,2018,3,152.949261,146.642449,201803,120.639207,124.195251,148.339606,154.299458,232.832843
255,255,2018,4,146.428229,152.493728,201804,152.949261,120.639207,124.195251,155.587546,183.892476
256,256,2018,5,178.425456,184.283251,201805,146.428229,152.949261,120.639207,150.122991,183.555789
257,257,2018,6,189.152015,199.374624,201806,178.425456,146.428229,152.949261,148.339606,164.909385
258,258,2018,7,210.708161,226.676860,201807,189.152015,178.425456,146.428229,124.195251,129.750907

In [23]:
EPU_World=EPU[['Date','EPU_World','EPU_World-1','EPU_World-2',
                                     'EPU_World-3','EPU_World-6','EPU_World-12']]

EPU_World=EPU_World.dropna()
EPU_World

,Date,EPU_World,EPU_World-1,EPU_World-2,EPU_World-3,EPU_World-6,EPU_World-12
12,199801,96.828275,104.295953,93.205424,82.110431,65.854587,79.887326
13,199802,86.752832,96.828275,104.295953,93.205424,64.929356,83.145863
14,199803,89.827865,86.752832,96.828275,104.295953,68.045255,71.464942
15,199804,79.984998,89.827865,86.752832,96.828275,82.110431,77.521001
16,199805,86.817065,79.984998,89.827865,86.752832,93.205424,73.366201
17,199806,85.903175,86.817065,79.984998,89.827865,104.295953,81.379689
18,199807,103.423216,85.903175,86.817065,79.984998,96.828275,65.854587
19,199808,117.423873,103.423216,85.903175,86.817065,86.752832,64.929356
20,199809,151.405519,117.423873,103.423216,85.903175,89.827865,68.045255
21,199810,120.175145,151.405519,117.423873,103.423216,79.984998,82.110431
22,199811,100.382400,120.175145,151.405519,117.423873,86.817065,93.205424
23,199812,95.699437,100.382400,120.175145,151.405519,85.903175,104.295953
24,199901,101.756229,95.699437,100.382400,120.175145,103.423216,96.828275
25,199902,82.085271,101.756229,95.699437,100.382400,117.423873,86.752832
26,199903,66.560508,82.085271,101.756229,95.699437,151.405519,89.827865
27,199904,65.799329,66.560508,82.085271,101.756229,120.175145,79.984998
28,199905,71.468466,65.799329,66.560508,82.085271,100.382400,86.817065
29,199906,74.525600,71.468466,65.799329,66.560508,95.699437,85.903175
30,199907,74.668331,74.525600,71.468466,65.799329,101.756229,103.423216
31,199908,65.304287,74.668331,74.525600,71.468466,82.085271,117.423873
32,199909,72.017542,65.304287,74.668331,74.525600,66.560508,151.405519
33,199910,67.814008,72.017542,65.304287,74.668331,65.799329,120.175145
34,199911,69.724464,67.814008,72.017542,65.304287,71.468466,100.382400
35,199912,62.694851,69.724464,67.814008,72.017542,74.525600,95.699437
36,200001,66.589573,62.694851,69.724464,67.814008,74.668331,101.756229
37,200002,61.355570,66.589573,62.694851,69.724464,65.304287,82.085271
38,200003,62.621199,61.355570,66.589573,62.694851,72.017542,66.560508
39,200004,64.277525,62.621199,61.355570,66.589573,67.814008,65.799329
40,200005,88.931012,64.277525,62.621199,61.355570,69.724464,71.468466
41,200006,91.233313,88.931012,64.277525,62.621199,62.694851,74.525600
...,...,...,...,...,...,...,...
229,201602,163.508727,156.064443,112.745006,95.912063,140.933731,108.206666
230,201603,171.201672,163.508727,156.064443,112.745006,192.516401,93.736800
231,201604,146.201912,171.201672,163.508727,156.064443,132.929122,101.033485
232,201605,137.765889,146.201912,171.201672,163.508727,95.912063,105.470778
233,201606,254.508211,137.765889,146.201912,171.201672,112.745006,114.230896
234,201607,264.740864,254.508211,137.765889,146.201912,156.064443,133.001067
235,201608,150.526471,264.740864,254.508211,137.765889,163.508727,140.933731
236,201609,161.389229,150.526471,264.740864,254.508211,171.201672,192.516401
237,201610,140.759020,161.389229,150.526471,264.740864,146.201912,132.929122
238,201611,271.403445,140.759020,161.389229,150.526471,137.765889,95.912063
239,201612,257.913450,271.403445,140.759020,161.389229,254.508211,112.745006
240,201701,283.258467,257.913450,271.403445,140.759020,264.740864,156.064443
241,201702,215.893940,283.258467,257.913450,271.403445,150.526471,163.508727
242,201703,232.832843,215.893940,283.258467,257.913450,161.389229,171.201672
243,201704,183.892476,232.832843,215.893940,283.258467,140.759020,146.201912
244,201705,183.555789,183.892476,232.832843,215.893940,271.403445,137.765889
245,201706,164.909385,183.555789,183.892476,232.832843,257.913450,254.508211
246,201707,129.750907,164.909385,183.555789,183.892476,283.258467,264.740864
247,201708,140.371505,129.750907,164.909385,183.555789,215.893940,150.526471
248,201709,154.299458,140.371505,129.750907,164.909385,232.832843,161.389229
249,201710,155.587546,154.299458,140.371505,129.750907,183.892476,140.759020
250,201711,150.122991,155.587546,154.299458,140.371505,183.555789,271.403445
251,201712,148.339606,150.122991,155.587546,154.299458,164.909385,257.913450
252,201801,124.195251,148.339606,150.122991,155.587546,129.750907,283.258467
253,201802,120.639207,124.195251,148.339606,150.122991,140.371505,215.893940
254,201803,152.949261,120.639207,124.195251,148.339606,154.299458,232.832843
255,201804,146.428229,152.949261,120.639207,124.195251,155.587546,183.892476
256,201805,178.425456,146.428229,152.949261,120.639207,150.122991,183.555789
257,201806,189.152015,178.425456,146.428229,152.949261,148.339606,164.909385
258,201807,210.708161,189.152015,178.425456,146.428229,124.195251,129.750907

In [24]:
EPU_World.to_excel('EPU_World.xlsx',index = False)