In [12]:
import numpy as np
import pandas as pd

In [13]:


xls = pd.ExcelFile('China_Policy_Uncertainty_Data.xlsx')
EPU = xls.parse('China EPU Index', header=0,index_col=None, na_values=['NA'])
#EPU Economic Politic Uncertainity

In [14]:
EPU

     year  month  China News-Based EPU
0    1995      1            192.911906
1    1995      2            193.987851
2    1995      3             88.227035
3    1995      4            131.034713
4    1995      5            177.096861
5    1995      6             79.096237
6    1995      7             61.732692
7    1995      8             52.983125
8    1995      9             76.820086
9    1995     10            153.871302
10   1995     11            100.061505
11   1995     12            143.116690
12   1996      1            128.429457
13   1996      2            111.158192
14   1996      3             69.440676
15   1996      4             63.357444
16   1996      5             84.173360
17   1996      6             36.838809
18   1996      7             47.684813
19   1996      8             55.953546
20   1996      9             51.041031
21   1996     10             53.619759
22   1996     11             85.299863
23   1996     12             69.185185
24   1997      1             88.323707
25   1997      2            115.348679
26   1997      3             59.410586
27   1997      4            123.271347
28   1997      5             20.579830
29   1997      6             62.723869
..    ...    ...                   ...
243  2015      4            105.318359
244  2015      5            127.552805
245  2015      6            123.343142
246  2015      7            268.709206
247  2015      8            224.058585
248  2015      9            393.234133
249  2015     10            244.867957
250  2015     11            104.749071
251  2015     12            151.614491
252  2016      1            261.942084
253  2016      2            269.019178
254  2016      3            323.155832
255  2016      4            286.177340
256  2016      5            260.257465
257  2016      6            357.208812
258  2016      7            558.222136
259  2016      8            288.780209
260  2016      9            388.749591
261  2016     10            261.898893
262  2016     11            475.670919
263  2016     12            646.910989
264  2017      1            694.849413
265  2017      2            464.522816
266  2017      3            533.304394
267  2017      4            322.344254
268  2017      5            451.978497
269  2017      6            328.553600
270  2017      7            162.693286
271  2017      8            265.258103
272  2017      9            264.654329

[273 rows x 3 columns]

In [15]:
EPU['Date']= EPU['year']*100+EPU['month'].astype(int)
#EPU['Date']

In [16]:
EPU=EPU.rename(columns = {'China News-Based EPU':'EPU_CHN'})
#Zaman Kaydırması Yapmak için kullanıyor. 
#Butun veri zaman ekseni açısından tam ve sıralandıktan sonra yapılması gerekiyor
EPU['EPU_CHN-1'] = EPU['EPU_CHN'] .shift(1)
EPU['EPU_CHN-2'] = EPU['EPU_CHN'].shift(2)
EPU['EPU_CHN-3'] = EPU['EPU_CHN'].shift(3)
EPU['EPU_CHN-6'] = EPU['EPU_CHN'].shift(6)
EPU['EPU_CHN-12'] = EPU['EPU_CHN'].shift(12)

In [17]:
EPU

,year,month,EPU_CHN,Date,EPU_CHN-1,EPU_CHN-2,EPU_CHN-3,EPU_CHN-6,EPU_CHN-12
0,1995,1,192.911906,199501,NaN,NaN,NaN,NaN,NaN
1,1995,2,193.987851,199502,192.911906,NaN,NaN,NaN,NaN
2,1995,3,88.227035,199503,193.987851,192.911906,NaN,NaN,NaN
3,1995,4,131.034713,199504,88.227035,193.987851,192.911906,NaN,NaN
4,1995,5,177.096861,199505,131.034713,88.227035,193.987851,NaN,NaN
5,1995,6,79.096237,199506,177.096861,131.034713,88.227035,NaN,NaN
6,1995,7,61.732692,199507,79.096237,177.096861,131.034713,192.911906,NaN
7,1995,8,52.983125,199508,61.732692,79.096237,177.096861,193.987851,NaN
8,1995,9,76.820086,199509,52.983125,61.732692,79.096237,88.227035,NaN
9,1995,10,153.871302,199510,76.820086,52.983125,61.732692,131.034713,NaN
10,1995,11,100.061505,199511,153.871302,76.820086,52.983125,177.096861,NaN
11,1995,12,143.116690,199512,100.061505,153.871302,76.820086,79.096237,NaN
12,1996,1,128.429457,199601,143.116690,100.061505,153.871302,61.732692,192.911906
13,1996,2,111.158192,199602,128.429457,143.116690,100.061505,52.983125,193.987851
14,1996,3,69.440676,199603,111.158192,128.429457,143.116690,76.820086,88.227035
15,1996,4,63.357444,199604,69.440676,111.158192,128.429457,153.871302,131.034713
16,1996,5,84.173360,199605,63.357444,69.440676,111.158192,100.061505,177.096861
17,1996,6,36.838809,199606,84.173360,63.357444,69.440676,143.116690,79.096237
18,1996,7,47.684813,199607,36.838809,84.173360,63.357444,128.429457,61.732692
19,1996,8,55.953546,199608,47.684813,36.838809,84.173360,111.158192,52.983125
20,1996,9,51.041031,199609,55.953546,47.684813,36.838809,69.440676,76.820086
21,1996,10,53.619759,199610,51.041031,55.953546,47.684813,63.357444,153.871302
22,1996,11,85.299863,199611,53.619759,51.041031,55.953546,84.173360,100.061505
23,1996,12,69.185185,199612,85.299863,53.619759,51.041031,36.838809,143.116690
24,1997,1,88.323707,199701,69.185185,85.299863,53.619759,47.684813,128.429457
25,1997,2,115.348679,199702,88.323707,69.185185,85.299863,55.953546,111.158192
26,1997,3,59.410586,199703,115.348679,88.323707,69.185185,51.041031,69.440676
27,1997,4,123.271347,199704,59.410586,115.348679,88.323707,53.619759,63.357444
28,1997,5,20.579830,199705,123.271347,59.410586,115.348679,85.299863,84.173360
29,1997,6,62.723869,199706,20.579830,123.271347,59.410586,69.185185,36.838809
...,...,...,...,...,...,...,...,...,...
243,2015,4,105.318359,201504,82.093294,117.683673,232.215104,240.495315,84.268257
244,2015,5,127.552805,201505,105.318359,82.093294,117.683673,112.738980,80.762770
245,2015,6,123.343142,201506,127.552805,105.318359,82.093294,93.960960,102.231655
246,2015,7,268.709206,201507,123.343142,127.552805,105.318359,232.215104,127.480291
247,2015,8,224.058585,201508,268.709206,123.343142,127.552805,117.683673,151.001907
248,2015,9,393.234133,201509,224.058585,268.709206,123.343142,82.093294,185.761899
249,2015,10,244.867957,201510,393.234133,224.058585,268.709206,105.318359,240.495315
250,2015,11,104.749071,201511,244.867957,393.234133,224.058585,127.552805,112.738980
251,2015,12,151.614491,201512,104.749071,244.867957,393.234133,123.343142,93.960960
252,2016,1,261.942084,201601,151.614491,104.749071,244.867957,268.709206,232.215104
253,2016,2,269.019178,201602,261.942084,151.614491,104.749071,224.058585,117.683673
254,2016,3,323.155832,201603,269.019178,261.942084,151.614491,393.234133,82.093294
255,2016,4,286.177340,201604,323.155832,269.019178,261.942084,244.867957,105.318359
256,2016,5,260.257465,201605,286.177340,323.155832,269.019178,104.749071,127.552805
257,2016,6,357.208812,201606,260.257465,286.177340,323.155832,151.614491,123.343142
258,2016,7,558.222136,201607,357.208812,260.257465,286.177340,261.942084,268.709206
259,2016,8,288.780209,201608,558.222136,357.208812,260.257465,269.019178,224.058585
260,2016,9,388.749591,201609,288.780209,558.222136,357.208812,323.155832,393.234133
261,2016,10,261.898893,201610,388.749591,288.780209,558.222136,286.177340,244.867957
262,2016,11,475.670919,201611,261.898893,388.749591,288.780209,260.257465,104.749071
263,2016,12,646.910989,201612,475.670919,261.898893,388.749591,357.208812,151.614491
264,2017,1,694.849413,201701,646.910989,475.670919,261.898893,558.222136,261.942084
265,2017,2,464.522816,201702,694.849413,646.910989,475.670919,288.780209,269.019178
266,2017,3,533.304394,201703,464.522816,694.849413,646.910989,388.749591,323.155832
267,2017,4,322.344254,201704,533.304394,464.522816,694.849413,261.898893,286.177340
268,2017,5,451.978497,201705,322.344254,533.304394,464.522816,475.670919,260.257465
269,2017,6,328.553600,201706,451.978497,322.344254,533.304394,646.910989,357.208812
270,2017,7,162.693286,201707,328.553600,451.978497,322.344254,694.849413,558.222136
271,2017,8,265.258103,201708,162.693286,328.553600,451.978497,464.522816,288.780209
272,2017,9,264.654329,201709,265.258103,162.693286,328.553600,533.304394,388.749591

In [18]:
EPU_CHN=EPU[['Date','EPU_CHN','EPU_CHN-1','EPU_CHN-2',
                                     'EPU_CHN-3','EPU_CHN-6','EPU_CHN-12']]

EPU_CHN=EPU_CHN.dropna()
EPU_CHN

,Date,EPU_CHN,EPU_CHN-1,EPU_CHN-2,EPU_CHN-3,EPU_CHN-6,EPU_CHN-12
12,199601,128.429457,143.116690,100.061505,153.871302,61.732692,192.911906
13,199602,111.158192,128.429457,143.116690,100.061505,52.983125,193.987851
14,199603,69.440676,111.158192,128.429457,143.116690,76.820086,88.227035
15,199604,63.357444,69.440676,111.158192,128.429457,153.871302,131.034713
16,199605,84.173360,63.357444,69.440676,111.158192,100.061505,177.096861
17,199606,36.838809,84.173360,63.357444,69.440676,143.116690,79.096237
18,199607,47.684813,36.838809,84.173360,63.357444,128.429457,61.732692
19,199608,55.953546,47.684813,36.838809,84.173360,111.158192,52.983125
20,199609,51.041031,55.953546,47.684813,36.838809,69.440676,76.820086
21,199610,53.619759,51.041031,55.953546,47.684813,63.357444,153.871302
22,199611,85.299863,53.619759,51.041031,55.953546,84.173360,100.061505
23,199612,69.185185,85.299863,53.619759,51.041031,36.838809,143.116690
24,199701,88.323707,69.185185,85.299863,53.619759,47.684813,128.429457
25,199702,115.348679,88.323707,69.185185,85.299863,55.953546,111.158192
26,199703,59.410586,115.348679,88.323707,69.185185,51.041031,69.440676
27,199704,123.271347,59.410586,115.348679,88.323707,53.619759,63.357444
28,199705,20.579830,123.271347,59.410586,115.348679,85.299863,84.173360
29,199706,62.723869,20.579830,123.271347,59.410586,69.185185,36.838809
30,199707,42.590281,62.723869,20.579830,123.271347,88.323707,47.684813
31,199708,27.126091,42.590281,62.723869,20.579830,115.348679,55.953546
32,199709,70.862670,27.126091,42.590281,62.723869,59.410586,51.041031
33,199710,83.157661,70.862670,27.126091,42.590281,123.271347,53.619759
34,199711,69.055750,83.157661,70.862670,27.126091,20.579830,85.299863
35,199712,20.722469,69.055750,83.157661,70.862670,62.723869,69.185185
36,199801,77.705830,20.722469,69.055750,83.157661,42.590281,88.323707
37,199802,98.684799,77.705830,20.722469,69.055750,27.126091,115.348679
38,199803,64.921202,98.684799,77.705830,20.722469,70.862670,59.410586
39,199804,19.439777,64.921202,98.684799,77.705830,83.157661,123.271347
40,199805,41.804219,19.439777,64.921202,98.684799,69.055750,20.579830
41,199806,68.298560,41.804219,19.439777,64.921202,20.722469,62.723869
...,...,...,...,...,...,...,...
243,201504,105.318359,82.093294,117.683673,232.215104,240.495315,84.268257
244,201505,127.552805,105.318359,82.093294,117.683673,112.738980,80.762770
245,201506,123.343142,127.552805,105.318359,82.093294,93.960960,102.231655
246,201507,268.709206,123.343142,127.552805,105.318359,232.215104,127.480291
247,201508,224.058585,268.709206,123.343142,127.552805,117.683673,151.001907
248,201509,393.234133,224.058585,268.709206,123.343142,82.093294,185.761899
249,201510,244.867957,393.234133,224.058585,268.709206,105.318359,240.495315
250,201511,104.749071,244.867957,393.234133,224.058585,127.552805,112.738980
251,201512,151.614491,104.749071,244.867957,393.234133,123.343142,93.960960
252,201601,261.942084,151.614491,104.749071,244.867957,268.709206,232.215104
253,201602,269.019178,261.942084,151.614491,104.749071,224.058585,117.683673
254,201603,323.155832,269.019178,261.942084,151.614491,393.234133,82.093294
255,201604,286.177340,323.155832,269.019178,261.942084,244.867957,105.318359
256,201605,260.257465,286.177340,323.155832,269.019178,104.749071,127.552805
257,201606,357.208812,260.257465,286.177340,323.155832,151.614491,123.343142
258,201607,558.222136,357.208812,260.257465,286.177340,261.942084,268.709206
259,201608,288.780209,558.222136,357.208812,260.257465,269.019178,224.058585
260,201609,388.749591,288.780209,558.222136,357.208812,323.155832,393.234133
261,201610,261.898893,388.749591,288.780209,558.222136,286.177340,244.867957
262,201611,475.670919,261.898893,388.749591,288.780209,260.257465,104.749071
263,201612,646.910989,475.670919,261.898893,388.749591,357.208812,151.614491
264,201701,694.849413,646.910989,475.670919,261.898893,558.222136,261.942084
265,201702,464.522816,694.849413,646.910989,475.670919,288.780209,269.019178
266,201703,533.304394,464.522816,694.849413,646.910989,388.749591,323.155832
267,201704,322.344254,533.304394,464.522816,694.849413,261.898893,286.177340
268,201705,451.978497,322.344254,533.304394,464.522816,475.670919,260.257465
269,201706,328.553600,451.978497,322.344254,533.304394,646.910989,357.208812
270,201707,162.693286,328.553600,451.978497,322.344254,694.849413,558.222136
271,201708,265.258103,162.693286,328.553600,451.978497,464.522816,288.780209
272,201709,264.654329,265.258103,162.693286,328.553600,533.304394,388.749591

In [19]:
EPU_CHN.to_excel('EPU_CHN.xlsx',index = False)