In [1]:
import numpy as np
import pandas as pd

In [3]:


xls = pd.ExcelFile('Global_Policy_Uncertainty_Data.xlsx')
EPU = xls.parse('Sheet1', header=0,index_col=None, na_values=['NA'])
#EPU Economic Politic Uncertainity

In [3]:
EPU

            Global EPU Index with Current Price GDP Weights  \
Year Month                                              NaN
1997 1                                            78.882823
     2                                            82.171981
     3                                            69.785820
     4                                            75.090517
     5                                            70.523377
     6                                            78.175609
     7                                            64.210996
     8                                            62.751583
     9                                            67.347860
     10                                           81.918654
     11                                           96.130732
     12                                          106.674380
1998 1                                            98.148487
     2                                            86.732059
     3                                            86.870726
     4                                            78.526715
     5                                            84.580479
     6                                            83.275092
     7                                           100.749456
     8                                           114.492838
     9                                           145.010139
     10                                          118.732840
     11                                           97.615918
     12                                           92.333622
1999 1                                            98.457543
     2                                            81.233302
     3                                            65.220573
     4                                            63.067116
     5                                            70.677621
...                                                     ...
2015 4                                           102.454948
     5                                           107.100262
     6                                           115.819713
     7                                           134.724076
     8                                           142.430512
     9                                           195.309983
     10                                          135.366755
     11                                           97.839581
     12                                          113.477754
2016 1                                           159.008521
     2                                           166.236308
     3                                           173.872326
     4                                           148.575866
     5                                           140.732778
     6                                           260.307749
     7                                           272.303330
     8                                           153.303782
     9                                           164.949518
     10                                          144.986998
     11                                          277.809405
     12                                          261.548327
2017 1                                           288.407126
     2                                           220.558672
     3                                           235.089841
     4                                           188.145601
     5                                           190.005154
     6                                           171.764314
     7                                           132.428044
     8                                           142.759920
     9                                           148.784698

            Global EPU Index with   PPP-adjusted GDP Weights
Year Month                                               NaN
1997 1                                             83.362911
     2                                             85.615057
     3                                             69.016810
     4                                             77.991852
     5                                             71.575473
     6                                             79.508703
     7                                             61.361763
     8                                             57.502813
     9                                             63.805862
     10                                            77.935280
     11                                            88.852036
     12                                            94.887813
1998 1                                             93.263329
     2                                             83.670802
     3                                             81.564231
     4                                             71.034652
     5                                             77.476402
     6                                             78.571372
     7                                             96.087667
     8                                            107.023414
     9                                            144.044503
     10                                           114.149428
     11                                            90.365403
     12                                            89.556844
1999 1                                             98.452812
     2                                             79.328743
     3                                             62.319667
     4                                             57.307840
     5                                             72.221964
...                                                      ...
2015 4                                            101.460268
     5                                            104.259348
     6                                            113.059688
     7                                            137.013665
     8                                            145.331511
     9                                            207.407453
     10                                           139.705348
     11                                            95.780957
     12                                           117.988930
2016 1                                            158.775705
     2                                            169.498283
     3                                            181.829369
     4                                            155.603410
     5                                            141.915009
     6                                            255.033741
     7                                            274.512667
     8                                            160.669484
     9                                            176.553818
     10                                           144.046951
     11                                           274.420264
     12                                           286.277174
2017 1                                            309.884468
     2                                            237.361666
     3                                            253.195571
     4                                            192.893629
     5                                            200.444854
     6                                            172.194778
     7                                            128.188174
     8                                            144.097846
     9                                            155.677640

[250 rows x 2 columns]

In [4]:
EPU=EPU.reset_index()
EPU=EPU.dropna()

In [5]:
EPU

,level_0,level_1,Global EPU Index with Current Price GDP Weights,Global EPU Index with PPP-adjusted GDP Weights
1,1997,1,78.882823,83.362911
2,1997,2,82.171981,85.615057
3,1997,3,69.785820,69.016810
4,1997,4,75.090517,77.991852
5,1997,5,70.523377,71.575473
6,1997,6,78.175609,79.508703
7,1997,7,64.210996,61.361763
8,1997,8,62.751583,57.502813
9,1997,9,67.347860,63.805862
10,1997,10,81.918654,77.935280
11,1997,11,96.130732,88.852036
12,1997,12,106.674380,94.887813
13,1998,1,98.148487,93.263329
14,1998,2,86.732059,83.670802
15,1998,3,86.870726,81.564231
16,1998,4,78.526715,71.034652
17,1998,5,84.580479,77.476402
18,1998,6,83.275092,78.571372
19,1998,7,100.749456,96.087667
20,1998,8,114.492838,107.023414
21,1998,9,145.010139,144.044503
22,1998,10,118.732840,114.149428
23,1998,11,97.615918,90.365403
24,1998,12,92.333622,89.556844
25,1999,1,98.457543,98.452812
26,1999,2,81.233302,79.328743
27,1999,3,65.220573,62.319667
28,1999,4,63.067116,57.307840
29,1999,5,70.677621,72.221964
30,1999,6,72.091865,71.819129
...,...,...,...,...
220,2015,4,102.454948,101.460268
221,2015,5,107.100262,104.259348
222,2015,6,115.819713,113.059688
223,2015,7,134.724076,137.013665
224,2015,8,142.430512,145.331511
225,2015,9,195.309983,207.407453
226,2015,10,135.366755,139.705348
227,2015,11,97.839581,95.780957
228,2015,12,113.477754,117.988930
229,2016,1,159.008521,158.775705
230,2016,2,166.236308,169.498283
231,2016,3,173.872326,181.829369
232,2016,4,148.575866,155.603410
233,2016,5,140.732778,141.915009
234,2016,6,260.307749,255.033741
235,2016,7,272.303330,274.512667
236,2016,8,153.303782,160.669484
237,2016,9,164.949518,176.553818
238,2016,10,144.986998,144.046951
239,2016,11,277.809405,274.420264
240,2016,12,261.548327,286.277174
241,2017,1,288.407126,309.884468
242,2017,2,220.558672,237.361666
243,2017,3,235.089841,253.195571
244,2017,4,188.145601,192.893629
245,2017,5,190.005154,200.444854
246,2017,6,171.764314,172.194778
247,2017,7,132.428044,128.188174
248,2017,8,142.759920,144.097846
249,2017,9,148.784698,155.677640

In [6]:
EPU['Date']= (EPU['level_0'].astype(int))*100+EPU['level_1'].astype(int)
#EPU['level_0']*2
#EPU['level_1']
EPU

,level_0,level_1,Global EPU Index with Current Price GDP Weights,Global EPU Index with PPP-adjusted GDP Weights,Date
1,1997,1,78.882823,83.362911,199701
2,1997,2,82.171981,85.615057,199702
3,1997,3,69.785820,69.016810,199703
4,1997,4,75.090517,77.991852,199704
5,1997,5,70.523377,71.575473,199705
6,1997,6,78.175609,79.508703,199706
7,1997,7,64.210996,61.361763,199707
8,1997,8,62.751583,57.502813,199708
9,1997,9,67.347860,63.805862,199709
10,1997,10,81.918654,77.935280,199710
11,1997,11,96.130732,88.852036,199711
12,1997,12,106.674380,94.887813,199712
13,1998,1,98.148487,93.263329,199801
14,1998,2,86.732059,83.670802,199802
15,1998,3,86.870726,81.564231,199803
16,1998,4,78.526715,71.034652,199804
17,1998,5,84.580479,77.476402,199805
18,1998,6,83.275092,78.571372,199806
19,1998,7,100.749456,96.087667,199807
20,1998,8,114.492838,107.023414,199808
21,1998,9,145.010139,144.044503,199809
22,1998,10,118.732840,114.149428,199810
23,1998,11,97.615918,90.365403,199811
24,1998,12,92.333622,89.556844,199812
25,1999,1,98.457543,98.452812,199901
26,1999,2,81.233302,79.328743,199902
27,1999,3,65.220573,62.319667,199903
28,1999,4,63.067116,57.307840,199904
29,1999,5,70.677621,72.221964,199905
30,1999,6,72.091865,71.819129,199906
...,...,...,...,...,...
220,2015,4,102.454948,101.460268,201504
221,2015,5,107.100262,104.259348,201505
222,2015,6,115.819713,113.059688,201506
223,2015,7,134.724076,137.013665,201507
224,2015,8,142.430512,145.331511,201508
225,2015,9,195.309983,207.407453,201509
226,2015,10,135.366755,139.705348,201510
227,2015,11,97.839581,95.780957,201511
228,2015,12,113.477754,117.988930,201512
229,2016,1,159.008521,158.775705,201601
230,2016,2,166.236308,169.498283,201602
231,2016,3,173.872326,181.829369,201603
232,2016,4,148.575866,155.603410,201604
233,2016,5,140.732778,141.915009,201605
234,2016,6,260.307749,255.033741,201606
235,2016,7,272.303330,274.512667,201607
236,2016,8,153.303782,160.669484,201608
237,2016,9,164.949518,176.553818,201609
238,2016,10,144.986998,144.046951,201610
239,2016,11,277.809405,274.420264,201611
240,2016,12,261.548327,286.277174,201612
241,2017,1,288.407126,309.884468,201701
242,2017,2,220.558672,237.361666,201702
243,2017,3,235.089841,253.195571,201703
244,2017,4,188.145601,192.893629,201704
245,2017,5,190.005154,200.444854,201705
246,2017,6,171.764314,172.194778,201706
247,2017,7,132.428044,128.188174,201707
248,2017,8,142.759920,144.097846,201708
249,2017,9,148.784698,155.677640,201709

In [7]:
EPU=EPU.rename(columns = {'Global EPU Index with Current Price GDP Weights':'EPU_World'})
#Zaman Kaydırması Yapmak için kullanıyor. 
#Butun veri zaman ekseni açısından tam ve sıralandıktan sonra yapılması gerekiyor
EPU['EPU_World-1'] = EPU['EPU_World'] .shift(1)
EPU['EPU_World-2'] = EPU['EPU_World'].shift(2)
EPU['EPU_World-3'] = EPU['EPU_World'].shift(3)
EPU['EPU_World-6'] = EPU['EPU_World'].shift(6)
EPU['EPU_World-12'] = EPU['EPU_World'].shift(12)

In [8]:
EPU

,level_0,level_1,EPU_World,Global EPU Index with PPP-adjusted GDP Weights,Date,EPU_World-1,EPU_World-2,EPU_World-3,EPU_World-6,EPU_World-12
1,1997,1,78.882823,83.362911,199701,NaN,NaN,NaN,NaN,NaN
2,1997,2,82.171981,85.615057,199702,78.882823,NaN,NaN,NaN,NaN
3,1997,3,69.785820,69.016810,199703,82.171981,78.882823,NaN,NaN,NaN
4,1997,4,75.090517,77.991852,199704,69.785820,82.171981,78.882823,NaN,NaN
5,1997,5,70.523377,71.575473,199705,75.090517,69.785820,82.171981,NaN,NaN
6,1997,6,78.175609,79.508703,199706,70.523377,75.090517,69.785820,NaN,NaN
7,1997,7,64.210996,61.361763,199707,78.175609,70.523377,75.090517,78.882823,NaN
8,1997,8,62.751583,57.502813,199708,64.210996,78.175609,70.523377,82.171981,NaN
9,1997,9,67.347860,63.805862,199709,62.751583,64.210996,78.175609,69.785820,NaN
10,1997,10,81.918654,77.935280,199710,67.347860,62.751583,64.210996,75.090517,NaN
11,1997,11,96.130732,88.852036,199711,81.918654,67.347860,62.751583,70.523377,NaN
12,1997,12,106.674380,94.887813,199712,96.130732,81.918654,67.347860,78.175609,NaN
13,1998,1,98.148487,93.263329,199801,106.674380,96.130732,81.918654,64.210996,78.882823
14,1998,2,86.732059,83.670802,199802,98.148487,106.674380,96.130732,62.751583,82.171981
15,1998,3,86.870726,81.564231,199803,86.732059,98.148487,106.674380,67.347860,69.785820
16,1998,4,78.526715,71.034652,199804,86.870726,86.732059,98.148487,81.918654,75.090517
17,1998,5,84.580479,77.476402,199805,78.526715,86.870726,86.732059,96.130732,70.523377
18,1998,6,83.275092,78.571372,199806,84.580479,78.526715,86.870726,106.674380,78.175609
19,1998,7,100.749456,96.087667,199807,83.275092,84.580479,78.526715,98.148487,64.210996
20,1998,8,114.492838,107.023414,199808,100.749456,83.275092,84.580479,86.732059,62.751583
21,1998,9,145.010139,144.044503,199809,114.492838,100.749456,83.275092,86.870726,67.347860
22,1998,10,118.732840,114.149428,199810,145.010139,114.492838,100.749456,78.526715,81.918654
23,1998,11,97.615918,90.365403,199811,118.732840,145.010139,114.492838,84.580479,96.130732
24,1998,12,92.333622,89.556844,199812,97.615918,118.732840,145.010139,83.275092,106.674380
25,1999,1,98.457543,98.452812,199901,92.333622,97.615918,118.732840,100.749456,98.148487
26,1999,2,81.233302,79.328743,199902,98.457543,92.333622,97.615918,114.492838,86.732059
27,1999,3,65.220573,62.319667,199903,81.233302,98.457543,92.333622,145.010139,86.870726
28,1999,4,63.067116,57.307840,199904,65.220573,81.233302,98.457543,118.732840,78.526715
29,1999,5,70.677621,72.221964,199905,63.067116,65.220573,81.233302,97.615918,84.580479
30,1999,6,72.091865,71.819129,199906,70.677621,63.067116,65.220573,92.333622,83.275092
...,...,...,...,...,...,...,...,...,...,...
220,2015,4,102.454948,101.460268,201504,94.136015,109.788720,142.657251,125.713271,91.900201
221,2015,5,107.100262,104.259348,201505,102.454948,94.136015,109.788720,107.670586,100.678988
222,2015,6,115.819713,113.059688,201506,107.100262,102.454948,94.136015,111.275067,81.466334
223,2015,7,134.724076,137.013665,201507,115.819713,107.100262,102.454948,142.657251,90.714700
224,2015,8,142.430512,145.331511,201508,134.724076,115.819713,107.100262,109.788720,101.970280
225,2015,9,195.309983,207.407453,201509,142.430512,134.724076,115.819713,94.136015,125.516515
226,2015,10,135.366755,139.705348,201510,195.309983,142.430512,134.724076,102.454948,125.713271
227,2015,11,97.839581,95.780957,201511,135.366755,195.309983,142.430512,107.100262,107.670586
228,2015,12,113.477754,117.988930,201512,97.839581,135.366755,195.309983,115.819713,111.275067
229,2016,1,159.008521,158.775705,201601,113.477754,97.839581,135.366755,134.724076,142.657251
230,2016,2,166.236308,169.498283,201602,159.008521,113.477754,97.839581,142.430512,109.788720
231,2016,3,173.872326,181.829369,201603,166.236308,159.008521,113.477754,195.309983,94.136015
232,2016,4,148.575866,155.603410,201604,173.872326,166.236308,159.008521,135.366755,102.454948
233,2016,5,140.732778,141.915009,201605,148.575866,173.872326,166.236308,97.839581,107.100262
234,2016,6,260.307749,255.033741,201606,140.732778,148.575866,173.872326,113.477754,115.819713
235,2016,7,272.303330,274.512667,201607,260.307749,140.732778,148.575866,159.008521,134.724076
236,2016,8,153.303782,160.669484,201608,272.303330,260.307749,140.732778,166.236308,142.430512
237,2016,9,164.949518,176.553818,201609,153.303782,272.303330,260.307749,173.872326,195.309983
238,2016,10,144.986998,144.046951,201610,164.949518,153.303782,272.303330,148.575866,135.366755
239,2016,11,277.809405,274.420264,201611,144.986998,164.949518,153.303782,140.732778,97.839581
240,2016,12,261.548327,286.277174,201612,277.809405,144.986998,164.949518,260.307749,113.477754
241,2017,1,288.407126,309.884468,201701,261.548327,277.809405,144.986998,272.303330,159.008521
242,2017,2,220.558672,237.361666,201702,288.407126,261.548327,277.809405,153.303782,166.236308
243,2017,3,235.089841,253.195571,201703,220.558672,288.407126,261.548327,164.949518,173.872326
244,2017,4,188.145601,192.893629,201704,235.089841,220.558672,288.407126,144.986998,148.575866
245,2017,5,190.005154,200.444854,201705,188.145601,235.089841,220.558672,277.809405,140.732778
246,2017,6,171.764314,172.194778,201706,190.005154,188.145601,235.089841,261.548327,260.307749
247,2017,7,132.428044,128.188174,201707,171.764314,190.005154,188.145601,288.407126,272.303330
248,2017,8,142.759920,144.097846,201708,132.428044,171.764314,190.005154,220.558672,153.303782
249,2017,9,148.784698,155.677640,201709,142.759920,132.428044,171.764314,235.089841,164.949518

In [9]:
EPU_World=EPU[['Date','EPU_World','EPU_World-1','EPU_World-2',
                                     'EPU_World-3','EPU_World-6','EPU_World-12']]

EPU_World=EPU_World.dropna()
EPU_World

,Date,EPU_World,EPU_World-1,EPU_World-2,EPU_World-3,EPU_World-6,EPU_World-12
13,199801,98.148487,106.674380,96.130732,81.918654,64.210996,78.882823
14,199802,86.732059,98.148487,106.674380,96.130732,62.751583,82.171981
15,199803,86.870726,86.732059,98.148487,106.674380,67.347860,69.785820
16,199804,78.526715,86.870726,86.732059,98.148487,81.918654,75.090517
17,199805,84.580479,78.526715,86.870726,86.732059,96.130732,70.523377
18,199806,83.275092,84.580479,78.526715,86.870726,106.674380,78.175609
19,199807,100.749456,83.275092,84.580479,78.526715,98.148487,64.210996
20,199808,114.492838,100.749456,83.275092,84.580479,86.732059,62.751583
21,199809,145.010139,114.492838,100.749456,83.275092,86.870726,67.347860
22,199810,118.732840,145.010139,114.492838,100.749456,78.526715,81.918654
23,199811,97.615918,118.732840,145.010139,114.492838,84.580479,96.130732
24,199812,92.333622,97.615918,118.732840,145.010139,83.275092,106.674380
25,199901,98.457543,92.333622,97.615918,118.732840,100.749456,98.148487
26,199902,81.233302,98.457543,92.333622,97.615918,114.492838,86.732059
27,199903,65.220573,81.233302,98.457543,92.333622,145.010139,86.870726
28,199904,63.067116,65.220573,81.233302,98.457543,118.732840,78.526715
29,199905,70.677621,63.067116,65.220573,81.233302,97.615918,84.580479
30,199906,72.091865,70.677621,63.067116,65.220573,92.333622,83.275092
31,199907,72.999155,72.091865,70.677621,63.067116,98.457543,100.749456
32,199908,61.522555,72.999155,72.091865,70.677621,81.233302,114.492838
33,199909,66.920314,61.522555,72.999155,72.091865,65.220573,145.010139
34,199910,65.574594,66.920314,61.522555,72.999155,63.067116,118.732840
35,199911,68.131660,65.574594,66.920314,61.522555,70.677621,97.615918
36,199912,59.918984,68.131660,65.574594,66.920314,72.091865,92.333622
37,200001,63.648636,59.918984,68.131660,65.574594,72.999155,98.457543
38,200002,57.928732,63.648636,59.918984,68.131660,61.522555,81.233302
39,200003,60.789851,57.928732,63.648636,59.918984,66.920314,65.220573
40,200004,62.994774,60.789851,57.928732,63.648636,65.574594,63.067116
41,200005,87.477222,62.994774,60.789851,57.928732,68.131660,70.677621
42,200006,88.292933,87.477222,62.994774,60.789851,59.918984,72.091865
...,...,...,...,...,...,...,...
220,201504,102.454948,94.136015,109.788720,142.657251,125.713271,91.900201
221,201505,107.100262,102.454948,94.136015,109.788720,107.670586,100.678988
222,201506,115.819713,107.100262,102.454948,94.136015,111.275067,81.466334
223,201507,134.724076,115.819713,107.100262,102.454948,142.657251,90.714700
224,201508,142.430512,134.724076,115.819713,107.100262,109.788720,101.970280
225,201509,195.309983,142.430512,134.724076,115.819713,94.136015,125.516515
226,201510,135.366755,195.309983,142.430512,134.724076,102.454948,125.713271
227,201511,97.839581,135.366755,195.309983,142.430512,107.100262,107.670586
228,201512,113.477754,97.839581,135.366755,195.309983,115.819713,111.275067
229,201601,159.008521,113.477754,97.839581,135.366755,134.724076,142.657251
230,201602,166.236308,159.008521,113.477754,97.839581,142.430512,109.788720
231,201603,173.872326,166.236308,159.008521,113.477754,195.309983,94.136015
232,201604,148.575866,173.872326,166.236308,159.008521,135.366755,102.454948
233,201605,140.732778,148.575866,173.872326,166.236308,97.839581,107.100262
234,201606,260.307749,140.732778,148.575866,173.872326,113.477754,115.819713
235,201607,272.303330,260.307749,140.732778,148.575866,159.008521,134.724076
236,201608,153.303782,272.303330,260.307749,140.732778,166.236308,142.430512
237,201609,164.949518,153.303782,272.303330,260.307749,173.872326,195.309983
238,201610,144.986998,164.949518,153.303782,272.303330,148.575866,135.366755
239,201611,277.809405,144.986998,164.949518,153.303782,140.732778,97.839581
240,201612,261.548327,277.809405,144.986998,164.949518,260.307749,113.477754
241,201701,288.407126,261.548327,277.809405,144.986998,272.303330,159.008521
242,201702,220.558672,288.407126,261.548327,277.809405,153.303782,166.236308
243,201703,235.089841,220.558672,288.407126,261.548327,164.949518,173.872326
244,201704,188.145601,235.089841,220.558672,288.407126,144.986998,148.575866
245,201705,190.005154,188.145601,235.089841,220.558672,277.809405,140.732778
246,201706,171.764314,190.005154,188.145601,235.089841,261.548327,260.307749
247,201707,132.428044,171.764314,190.005154,188.145601,288.407126,272.303330
248,201708,142.759920,132.428044,171.764314,190.005154,220.558672,153.303782
249,201709,148.784698,142.759920,132.428044,171.764314,235.089841,164.949518

In [10]:
EPU_World.to_excel('EPU_World.xlsx',index = False)